apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.gustsmotion'
version = '0.1.0'

def expoModulesCorePlugin = new File(
  project(":expo-modules-core").projectDir.absolutePath,
  "ExpoModulesCorePlugin.gradle"
)
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()

def getExtOrDefault(name) {
  ext.has(name) ? ext.get(name) : (rootProject.ext.has(name) ? rootProject.ext.get(name) : null)
}

android {
  namespace "expo.modules.gustsmotion"
  compileSdkVersion getExtOrDefault('compileSdkVersion') ?: 35

  defaultConfig {
    minSdkVersion getExtOrDefault('minSdkVersion') ?: 24
    targetSdkVersion getExtOrDefault('targetSdkVersion') ?: 35
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

repositories {
  mavenCentral()
}

dependencies {
}
