// ============================================================
// GUSTS - Base de datos de spots de kitesurf en Latinoamérica
// ------------------------------------------------------------
// water:  'plana' | 'choppy' | 'olas' | 'mixta'
// level:  'Principiante' | 'Intermedio' | 'Avanzado' | 'Experto' | 'Todos'
// Las coordenadas son aproximadas (centro de la zona de navegación).
// Ajustalas si tenés el punto exacto de la playa/lanzamiento.
// ============================================================

export const SPOTS = [
  // ---------- BRASIL ----------
  {
    id: 'br-cumbuco',
    name: 'Cumbuco',
    region: 'Ceará',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -3.6167, lng: -38.7333,
    water: 'mixta',
    waterDesc: 'Agua plana en la laguna; choppy y ola corta en el mar.',
    wind: 'SE / ESE',
    windMin: 18, windMax: 28,
    level: 'Todos',
  },
  {
    id: 'br-jeri',
    name: 'Jericoacoara',
    region: 'Ceará',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -2.7961, lng: -40.5136,
    water: 'choppy',
    waterDesc: 'Choppy con olas medianas en el mar.',
    wind: 'E / ESE',
    windMin: 22, windMax: 35,
    level: 'Intermedio',
  },
  {
    id: 'br-prea',
    name: 'Preá',
    region: 'Ceará',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -2.8167, lng: -40.4167,
    water: 'olas',
    waterDesc: 'Choppy fuerte y olas de 1 a 2 metros.',
    wind: 'E / ESE',
    windMin: 25, windMax: 35,
    level: 'Intermedio',
  },
  {
    id: 'br-taiba',
    name: 'Taíba',
    region: 'Ceará',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -3.5167, lng: -38.9167,
    water: 'plana',
    waterDesc: 'Laguna de agua súper plana y playa de olas.',
    wind: 'E / ESE',
    windMin: 20, windMax: 30,
    level: 'Todos',
  },
  {
    id: 'br-paracuru',
    name: 'Paracuru',
    region: 'Ceará',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -3.4100, lng: -39.0300,
    water: 'mixta',
    waterDesc: 'Agua plana con marea baja; olas excelentes fuera del arrecife.',
    wind: 'E / ESE',
    windMin: 20, windMax: 30,
    level: 'Intermedio',
  },
  {
    id: 'br-barra-grande',
    name: 'Barra Grande',
    region: 'Piauí',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -2.9236, lng: -41.3400,
    water: 'mixta',
    waterDesc: 'Laguna muy plana e itinerarios en mar choppy.',
    wind: 'E / ESE',
    windMin: 18, windMax: 28,
    level: 'Todos',
  },
  {
    id: 'br-atins',
    name: 'Atins',
    region: 'Maranhão',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -2.5786, lng: -42.7386,
    water: 'plana',
    waterDesc: 'Bancos de arena de agua 100% plana y pequeñas olas de marea.',
    wind: 'E / NE',
    windMin: 18, windMax: 25,
    level: 'Todos',
  },
  {
    id: 'br-gostoso',
    name: 'São Miguel do Gostoso',
    region: 'Rio Grande do Norte',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -5.1236, lng: -35.6350,
    water: 'mixta',
    waterDesc: 'Choppy suave con zonas de ola en arrecife.',
    wind: 'E / SE',
    windMin: 18, windMax: 28,
    level: 'Todos',
  },
  {
    id: 'br-lagoa',
    name: 'Lagoa da Conceição',
    region: 'Florianópolis, SC',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -27.6000, lng: -48.4667,
    water: 'plana',
    waterDesc: 'Agua dulce/salobre plana a choppy leve.',
    wind: 'S / N',
    windMin: 12, windMax: 22,
    level: 'Principiante',
  },
  {
    id: 'br-campeche',
    name: 'Campeche',
    region: 'Florianópolis, SC',
    country: 'Brasil',
    flag: '🇧🇷',
    lat: -27.6750, lng: -48.4800,
    water: 'olas',
    waterDesc: 'Olas potentes de mar abierto (waveriding).',
    wind: 'S / SE',
    windMin: 15, windMax: 25,
    level: 'Experto',
  },

  // ---------- ARGENTINA ----------
  {
    id: 'ar-cuesta',
    name: 'Cuesta del Viento',
    region: 'Rodeo, San Juan',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -30.1881, lng: -69.0742,
    water: 'choppy',
    waterDesc: 'Dique de agua dulce con chop picado y fuerte. Efecto venturi por el encajonamiento del valle.',
    wind: 'O / SO',
    windMin: 25, windMax: 45,
    level: 'Experto',
    caution: 'Extremadamente ventoso. El viento entra de golpe al mediodia. Costa con piedras filosas: equipo chico (5m a 7m).',
  },
  {
    id: 'ar-potrerillos',
    name: 'Potrerillos',
    region: 'Mendoza',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -32.9912, lng: -69.1834,
    water: 'choppy',
    waterDesc: 'Embalse de montana de agua dulce, chop suave. Termico de tarde.',
    wind: 'O / SO (termico)',
    windMin: 14, windMax: 25,
    level: 'Intermedio',
    caution: 'Costa de piedras, poco espacio para armar y agua fria de deshielo.',
  },
  {
    id: 'ar-peru-beach',
    name: 'Perú Beach / BA Kitebeach',
    region: 'Acassuso, Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.4709, lng: -58.4913,
    water: 'choppy',
    waterDesc: 'Rio de la Plata con agua picada y turbia. Navegacion onshore / side-shore.',
    wind: 'E / SE / NE / S',
    windMin: 10, windMax: 22,
    level: 'Todos',
    caution: 'Fondo de lodo y toscas duras. Con marea baja queda muy poca profundidad. Mucha concentracion de navegantes.',
  },
  {
    id: 'ar-punta-lara',
    name: 'Punta Lara',
    region: 'Ensenada, Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.8167, lng: -57.9833,
    water: 'choppy',
    waterDesc: 'Río con chop y corriente sostenida.',
    wind: 'E / SE',
    windMin: 12, windMax: 20,
    level: 'Principiante',
  },
  {
    id: 'ar-vasquita',
    name: 'La Vasquita Kite Spot',
    region: 'Magdalena, Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.9622, lng: -57.6279,
    water: 'choppy',
    waterDesc:
      'Río de la Plata exterior (estuario): agua dulce y marrón con chop corto y picado, ideal para saltar. La marea y la sudestada cambian mucho la altura del agua y dejan bancos de arena en la costa baja.',
    wind: 'SE / NE (side-shore)',
    windMin: 12, windMax: 22,
    level: 'Todos',
  },
  {
    id: 'ar-monte-hermoso',
    name: 'Monte Hermoso',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.9862, lng: -61.2921,
    water: 'olas',
    waterDesc: 'Mar abierto con olas medianas. Muy plana en marea baja. La playa mira al sur, asi que E y O entran side-shore.',
    wind: 'E / SE / S / SO / O',
    windMin: 14, windMax: 28,
    level: 'Todos',
    caution: 'Agua templada pero con medusas en verano.',
  },
  {
    id: 'ar-bariloche',
    name: 'Nahuel Huapi - Playa Centro',
    region: 'Bariloche, Río Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -41.1335, lng: -71.3103,
    water: 'choppy',
    waterDesc: 'Agua helada de deshielo y chop fuerte de lago.',
    wind: 'O / NO',
    windMin: 15, windMax: 35,
    level: 'Intermedio',
    caution: 'Costa de piedras, poco espacio de despegue y rafagas por los edificios y el arbolado.',
  },
  {
    id: 'ar-san-blas',
    name: 'Bahía San Blas',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -40.5500, lng: -62.2333,
    water: 'choppy',
    waterDesc: 'Mar picado con fuertes corrientes de marea.',
    wind: 'S / SW',
    windMin: 18, windMax: 30,
    level: 'Avanzado',
  },

  // ---------- COLOMBIA ----------
  {
    id: 'co-cabo-vela',
    name: 'Cabo de la Vela',
    region: 'La Guajira',
    country: 'Colombia',
    flag: '🇨🇴',
    lat: 12.2167, lng: -72.1667,
    water: 'plana',
    waterDesc: 'Agua ultra plana cerca de la costa (offshore / side-off).',
    wind: 'NE Alisios',
    windMin: 25, windMax: 40,
    level: 'Intermedio',
  },
  {
    id: 'co-mayapo',
    name: 'Mayapo',
    region: 'La Guajira',
    country: 'Colombia',
    flag: '🇨🇴',
    lat: 11.6333, lng: -72.6000,
    water: 'plana',
    waterDesc: 'Agua cristalina semi-plana con chop muy suave.',
    wind: 'NE',
    windMin: 20, windMax: 30,
    level: 'Todos',
  },
  {
    id: 'co-santa-veronica',
    name: 'Santa Verónica / Galerazamba',
    region: 'Atlántico',
    country: 'Colombia',
    flag: '🇨🇴',
    lat: 10.7667, lng: -75.2667,
    water: 'olas',
    waterDesc: 'Olas medianas a grandes con choppy para waveriding.',
    wind: 'NE',
    windMin: 20, windMax: 30,
    level: 'Intermedio',
  },
  {
    id: 'co-calima',
    name: 'Lago Calima',
    region: 'Valle del Cauca',
    country: 'Colombia',
    flag: '🇨🇴',
    lat: 3.9000, lng: -76.5000,
    water: 'choppy',
    waterDesc: 'Agua dulce picada de embalse térmico.',
    wind: 'S / SW',
    windMin: 18, windMax: 28,
    level: 'Todos',
  },

  // ---------- MÉXICO ----------
  {
    id: 'mx-la-ventana',
    name: 'La Ventana',
    region: 'Baja California Sur',
    country: 'México',
    flag: '🇲🇽',
    lat: 24.0500, lng: -109.9833,
    water: 'choppy',
    waterDesc: 'Choppy con swell largo en el canal.',
    wind: 'N / NW',
    windMin: 15, windMax: 25,
    level: 'Todos',
  },
  {
    id: 'mx-isla-blanca',
    name: 'Isla Blanca',
    region: 'Quintana Roo',
    country: 'México',
    flag: '🇲🇽',
    lat: 21.2500, lng: -86.8000,
    water: 'plana',
    waterDesc: 'Laguna de agua salada 100% plana y muy poco profunda.',
    wind: 'E / NE / N',
    windMin: 12, windMax: 22,
    level: 'Todos',
  },
  {
    id: 'mx-el-cuyo',
    name: 'El Cuyo',
    region: 'Yucatán',
    country: 'México',
    flag: '🇲🇽',
    lat: 21.5167, lng: -87.6833,
    water: 'plana',
    waterDesc: 'Agua poco profunda, plana a choppy suave según la marea.',
    wind: 'NE / E / N',
    windMin: 12, windMax: 25,
    level: 'Todos',
  },
  {
    id: 'mx-holbox',
    name: 'Holbox',
    region: 'Quintana Roo',
    country: 'México',
    flag: '🇲🇽',
    lat: 21.5333, lng: -87.3833,
    water: 'plana',
    waterDesc: 'Agua llana, cristalina y súper plana.',
    wind: 'NE / E',
    windMin: 12, windMax: 20,
    level: 'Principiante',
  },

  // ---------- PERÚ ----------
  {
    id: 'pe-paracas',
    name: 'Paracas',
    region: 'Ica',
    country: 'Perú',
    flag: '🇵🇪',
    lat: -13.8333, lng: -76.2500,
    water: 'plana',
    waterDesc: 'Bahía protegida de agua muy plana (Laguna Seca) y chop suave.',
    wind: 'S / SO (Paracas)',
    windMin: 18, windMax: 30,
    level: 'Todos',
  },
  {
    id: 'pe-mancora',
    name: 'Máncora',
    region: 'Piura',
    country: 'Perú',
    flag: '🇵🇪',
    lat: -4.1000, lng: -81.0500,
    water: 'olas',
    waterDesc: 'Mar picado con olas limpias en las puntas de arrecife.',
    wind: 'SO / S',
    windMin: 15, windMax: 22,
    level: 'Intermedio',
  },
  {
    id: 'pe-pacasmayo',
    name: 'Pacasmayo',
    region: 'La Libertad',
    country: 'Perú',
    flag: '🇵🇪',
    lat: -7.4000, lng: -79.5833,
    water: 'olas',
    waterDesc: 'Ola izquierda kilométrica de agua ordenada (waveriding).',
    wind: 'SO / S',
    windMin: 15, windMax: 22,
    level: 'Intermedio',
  },

  // ---------- CHILE ----------
  {
    id: 'cl-matanzas',
    name: 'Matanzas / Puertecillo',
    region: "O'Higgins",
    country: 'Chile',
    flag: '🇨🇱',
    lat: -33.9500, lng: -71.8667,
    water: 'olas',
    waterDesc: 'Mar del Pacífico frío con olas muy potentes y tubulares.',
    wind: 'S / SO',
    windMin: 18, windMax: 30,
    level: 'Experto',
  },
  {
    id: 'cl-puclaro',
    name: 'Embalse Puclaro',
    region: 'Coquimbo',
    country: 'Chile',
    flag: '🇨🇱',
    lat: -30.0000, lng: -70.8333,
    water: 'plana',
    waterDesc: 'Agua dulce plana a picada suave entre montañas.',
    wind: 'W / SW térmico',
    windMin: 18, windMax: 28,
    level: 'Todos',
  },

  // ---------- URUGUAY ----------
  {
    id: 'uy-laguna-rocha',
    name: 'Laguna de Rocha / Garzón',
    region: 'Rocha',
    country: 'Uruguay',
    flag: '🇺🇾',
    lat: -34.6500, lng: -54.2833,
    water: 'plana',
    waterDesc: 'Agua dulce/salobre completamente plana.',
    wind: 'NE / S',
    windMin: 12, windMax: 22,
    level: 'Todos',
  },
  {
    id: 'uy-jose-ignacio',
    name: 'José Ignacio',
    region: 'Maldonado',
    country: 'Uruguay',
    flag: '🇺🇾',
    lat: -34.8333, lng: -54.6333,
    water: 'olas',
    waterDesc: 'Mar abierto con olas moderadas.',
    wind: 'E / SO / S',
    windMin: 12, windMax: 22,
    level: 'Intermedio',
  },

  // ---------- VENEZUELA ----------
  {
    id: 've-el-yaque',
    name: 'El Yaque',
    region: 'Isla de Margarita',
    country: 'Venezuela',
    flag: '🇻🇪',
    lat: 10.9333, lng: -63.9833,
    water: 'mixta',
    waterDesc: 'Agua plana cerca de la playa, choppy mar adentro.',
    wind: 'E Alisios',
    windMin: 20, windMax: 30,
    level: 'Todos',
  },
  {
    id: 've-los-roques',
    name: 'Los Roques',
    region: 'Dependencias Federales',
    country: 'Venezuela',
    flag: '🇻🇪',
    lat: 11.9500, lng: -66.6667,
    water: 'plana',
    waterDesc: 'Cayos de arena con agua turquesa 100% plana.',
    wind: 'E / NE',
    windMin: 15, windMax: 22,
    level: 'Todos',
  },

  // ---------- COSTA RICA ----------
  {
    id: 'cr-bahia-salinas',
    name: 'Bahía Salinas',
    region: 'Guanacaste',
    country: 'Costa Rica',
    flag: '🇨🇷',
    lat: 11.0500, lng: -85.7333,
    water: 'choppy',
    waterDesc: 'Choppy a picado fuerte en mar abierto.',
    wind: 'E / NE Papagayo',
    windMin: 22, windMax: 38,
    level: 'Intermedio',
  },
  {
    id: 'cr-arenal',
    name: 'Lago Arenal',
    region: 'Guanacaste',
    country: 'Costa Rica',
    flag: '🇨🇷',
    lat: 10.5333, lng: -84.9167,
    water: 'choppy',
    waterDesc: 'Agua dulce picada con chop corto de embalse.',
    wind: 'E',
    windMin: 20, windMax: 35,
    level: 'Avanzado',
  },

  // ---------- PANAMÁ ----------
  {
    id: 'pa-punta-chame',
    name: 'Punta Chame',
    region: 'Panamá Oeste',
    country: 'Panamá',
    flag: '🇵🇦',
    lat: 8.6500, lng: -79.7000,
    water: 'mixta',
    waterDesc: 'Bahía de arena con agua plana en marea baja y chop en marea alta.',
    wind: 'N / NE',
    windMin: 15, windMax: 25,
    level: 'Todos',
  },

  // ---------- REPÚBLICA DOMINICANA ----------
  {
    id: 'do-cabarete',
    name: 'Cabarete',
    region: 'Puerto Plata',
    country: 'República Dominicana',
    flag: '🇩🇴',
    lat: 19.7500, lng: -70.4167,
    water: 'mixta',
    waterDesc: 'Choppy en la orilla y ola rompiente en el arrecife exterior.',
    wind: 'E / NE Alisios',
    windMin: 15, windMax: 25,
    level: 'Todos',
  },

  // ---------- ARGENTINA (spots locales) ----------
  {
    id: 'ar-acevedo',
    name: 'Acevedo',
    region: 'Santa Fe',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -33.2842, lng: -60.482,
    water: 'plana',
    waterDesc: 'Laguna de campo con agua plana; la profundidad varía bastante segun las lluvias.',
    wind: 'N / NE / S / SE',
    windMin: 12, windMax: 22,
    level: 'Principiante',
    caution: 'Vegetacion baja en la orilla y profundidad variable segun las lluvias.',
  },
  {
    id: 'ar-punta-de-fuego',
    name: 'Banquito Punta de Fuego',
    region: 'Rosario, Santa Fe',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -32.915, lng: -60.655,
    water: 'choppy',
    waterDesc: 'Isla en el Rio Parana con chop de rio y corriente marcada.',
    wind: 'SE / E / NE / S',
    windMin: 12, windMax: 25,
    level: 'Intermedio',
    caution: 'Corrientes rapidas, transito de embarcaciones y troncos flotantes.',
  },
  {
    id: 'ar-san-andres',
    name: 'Banquito San Andres',
    region: 'Rosario, Santa Fe',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -32.9281, lng: -60.6724,
    water: 'plana',
    waterDesc: 'Bancos de arena fina con agua plana en el Parana.',
    wind: 'E / SE / NE / S',
    windMin: 12, windMax: 25,
    level: 'Todos',
    caution: 'Se llega en lancha desde Rosario. Ojo con los cambios de corriente en el canal principal.',
  },
  {
    id: 'ar-carilo',
    name: 'Carilo',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.1645, lng: -56.8892,
    water: 'olas',
    waterDesc: 'Mar abierto con olas y rompiente fuerte.',
    wind: 'NE / E / SE / S',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Rompiente fuerte y deriva lateral con la marea. Prohibido navegar en zona de banistas en verano.',
  },
  {
    id: 'ar-claromeco',
    name: 'Claromeco',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.8572, lng: -60.0718,
    water: 'olas',
    waterDesc: 'Mar abierto con rompiente potente y corrientes intensas.',
    wind: 'E / SE / S / SO (side/onshore)',
    windMin: 15, windMax: 30,
    level: 'Avanzado',
    caution: 'Corrientes intensas y agua fria fuera de temporada.',
  },
  {
    id: 'ar-club7',
    name: 'Club 7 KSM',
    region: 'San Isidro, Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.4601, lng: -58.502,
    water: 'choppy',
    waterDesc: 'Rio de la Plata con chop suave y fondo lodoso.',
    wind: 'SE / E / NE',
    windMin: 10, windMax: 20,
    level: 'Principiante',
    caution: 'Rampa de despegue reducida. Fondo lodoso con juncales cerca de la orilla.',
  },
  {
    id: 'ar-dina-huapi',
    name: 'Dina Huapi',
    region: 'Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -41.0722, lng: -71.1642,
    water: 'choppy',
    waterDesc: 'Lago de deshielo con olas cortas y profundas.',
    wind: 'O / NO / SO',
    windMin: 15, windMax: 35,
    level: 'Intermedio',
    caution: 'Agua muy fria: neoprene 5/4mm. Playa de pedregullo.',
  },
  {
    id: 'ar-el-desierto',
    name: 'El Desierto',
    region: 'Acassuso, Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.4658, lng: -58.496,
    water: 'choppy',
    waterDesc: 'Rio de la Plata con chop y fondo de toscas.',
    wind: 'E / SE / S',
    windMin: 12, windMax: 22,
    level: 'Intermedio',
    caution: 'Toscas expuestas y juncos. Poco espacio para armar con marea alta.',
  },
  {
    id: 'ar-nihuil',
    name: 'El Nihuil',
    region: 'Mendoza',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -35.0298, lng: -68.6972,
    water: 'choppy',
    waterDesc: 'Embalse de altura con chop de lago.',
    wind: 'S / SO / SE / O',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Rafagas cambiantes cerca de la costa. Fondo de arena con piedras.',
  },
  {
    id: 'ar-torreon',
    name: 'El Torreon',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.0053, lng: -57.5381,
    water: 'olas',
    waterDesc: 'Rompiente fuerte junto a escolleras.',
    wind: 'E / SE / NE',
    windMin: 15, windMax: 28,
    level: 'Avanzado',
    caution: 'Escolleras de piedra muy cercanas. Mucha gente e infraestructura urbana.',
  },
  {
    id: 'ar-honu',
    name: 'Honu Beach',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.0862, lng: -57.546,
    water: 'olas',
    waterDesc: 'Oleaje fuerte de mar abierto.',
    wind: 'E / SE / S / NE',
    windMin: 15, windMax: 30,
    level: 'Intermedio',
    caution: 'Zona de surfistas. Corriente de deriva hacia las escolleras del sur.',
  },
  {
    id: 'ar-kitebeach-mdq',
    name: 'Kite Beach MDQ',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.0711, lng: -57.5458,
    water: 'olas',
    waterDesc: 'Oleaje de mar abierto en playa amplia.',
    wind: 'NE / E / SE',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Zona delimitada para deportes nauticos en verano.',
  },
  {
    id: 'ar-la-boca-condor',
    name: 'La Boca',
    region: 'Balneario El Condor, Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -41.0542, lng: -62.8335,
    water: 'mixta',
    waterDesc: 'Desembocadura con gran amplitud de marea.',
    wind: 'S / SE / E / NE',
    windMin: 18, windMax: 35,
    level: 'Intermedio',
    caution: 'Marea de gran amplitud, agua fria y rafagas intensas. Acantilados en algunos sectores.',
  },
  {
    id: 'ar-la-terraza',
    name: 'La Terraza',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.012, lng: -57.535,
    water: 'olas',
    waterDesc: 'Rompiente entre paredones y escolleras.',
    wind: 'E / SE / NE',
    windMin: 15, windMax: 28,
    level: 'Avanzado',
    caution: 'Espacio de playa muy reducido. Solo con buena marea.',
  },
  {
    id: 'ar-gutierrez',
    name: 'Lago Gutierrez',
    region: 'Bariloche, Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -41.182, lng: -71.411,
    water: 'choppy',
    waterDesc: 'Lago de montana con chop corto.',
    wind: 'O / SO',
    windMin: 12, windMax: 25,
    level: 'Intermedio',
    caution: 'Agua muy fria y rafagas encajonadas por los cerros.',
  },
  {
    id: 'ar-los-molinos',
    name: 'Lago Los Molinos',
    region: 'Potrero de Garay, Cordoba',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -31.7925, lng: -64.5411,
    water: 'choppy',
    waterDesc: 'Embalse serrano con chop segun la cota del agua.',
    wind: 'N / NE / S / SO',
    windMin: 12, windMax: 25,
    level: 'Todos',
    caution: 'Piedras y troncos sumergidos segun la cota. El viento sur entra fuerte y racheado.',
  },
  {
    id: 'ar-mar-chiquita-cba',
    name: 'Lago Mar Chiquita',
    region: 'Cordoba',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -30.6, lng: -62.6,
    water: 'plana',
    waterDesc: 'Agua salobre muy llana cerca de la costa.',
    wind: 'N / S / SE / NE',
    windMin: 12, windMax: 25,
    level: 'Principiante',
    caution: 'El nivel del agua cambia mucho; hay que mudarse de zona si baja demasiado.',
  },
  {
    id: 'ar-chascomus',
    name: 'Laguna Chascomus',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -35.5822, lng: -58.0169,
    water: 'plana',
    waterDesc: 'Laguna de agua dulce plana y poco profunda.',
    wind: 'Casi todas las direcciones',
    windMin: 10, windMax: 20,
    level: 'Principiante',
    caution: 'Fondo de barro, muy poca profundidad en la orilla y juncos. Evitar viento racheado del continente.',
  },
  {
    id: 'ar-mar-chiquita-laguna',
    name: 'Laguna Mar Chiquita',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.7523, lng: -57.4261,
    water: 'plana',
    waterDesc: 'Laguna costera plana dentro de reserva natural.',
    wind: 'NE / E / SE / S / SO',
    windMin: 12, windMax: 25,
    level: 'Principiante',
    caution: 'Reserva natural. Bancos de cangrejos, barro profundo en la orilla y bajantes.',
  },
  {
    id: 'ar-melincue',
    name: 'Laguna Melincue',
    region: 'Santa Fe',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -33.657, lng: -61.4642,
    water: 'plana',
    waterDesc: 'Laguna plana de agua dulce.',
    wind: 'N / S / SE / E',
    windMin: 12, windMax: 24,
    level: 'Principiante',
    caution: 'Poca profundidad en la zona de despegue y barro en el fondo.',
  },
  {
    id: 'ar-mar-azul',
    name: 'Mar Azul',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.3321, lng: -57.0261,
    water: 'olas',
    waterDesc: 'Rompiente de mar abierto entre medanos.',
    wind: 'NE / E / SE / S',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Sin guardavidas en los sectores alejados de medanos.',
  },
  {
    id: 'ar-mar-chiquita-mar',
    name: 'Mar Chiquita (sector mar)',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.745, lng: -57.408,
    water: 'olas',
    waterDesc: 'Boca de laguna con corrientes de marea hacia el mar.',
    wind: 'NE / E / SE / S',
    windMin: 15, windMax: 30,
    level: 'Avanzado',
    caution: 'Corrientes de marea muy fuertes cruzando hacia mar abierto.',
  },
  {
    id: 'ar-mar-de-cobo',
    name: 'Mar de Cobo',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.7621, lng: -57.442,
    water: 'olas',
    waterDesc: 'Mar abierto con olas medianas a grandes.',
    wind: 'NE / E / SE / S',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Deriva costera marcada.',
  },
  {
    id: 'ar-mirador9',
    name: 'Mirador 9',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.092, lng: -57.548,
    water: 'olas',
    waterDesc: 'Rompiente fuerte junto a acantilados.',
    wind: 'E / SE / S / NE',
    windMin: 15, windMax: 30,
    level: 'Avanzado',
    caution: 'Acantilados y piedras al sur de la playa.',
  },
  {
    id: 'ar-miramar',
    name: 'Miramar',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.2721, lng: -57.8381,
    water: 'olas',
    waterDesc: 'Mar abierto con rompiente y escolleras en el centro.',
    wind: 'E / SE / S / NE',
    windMin: 15, windMax: 30,
    level: 'Intermedio',
    caution: 'Las escolleras del sector centrico generan corrientes fuertes en marea alta.',
  },
  {
    id: 'ar-estacada',
    name: 'Estacada (Ragintuco)',
    region: 'Nahuel Huapi, Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -40.852, lng: -71.551,
    water: 'choppy',
    waterDesc: 'Lago con chop y playa muy angosta.',
    wind: 'O / SO',
    windMin: 15, windMax: 30,
    level: 'Avanzado',
    caution: 'Vegetacion densa detras de la playa y agua muy fria.',
  },
  {
    id: 'ar-brazo-huemul',
    name: 'Brazo Huemul',
    region: 'Nahuel Huapi, Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -40.951, lng: -71.42,
    water: 'choppy',
    waterDesc: 'Brazo de lago encajonado entre cerros.',
    wind: 'O / SO',
    windMin: 15, windMax: 32,
    level: 'Avanzado',
    caution: 'Viento racheado por la geografia. El autorescate a pie es imposible por los paredones de roca.',
  },
  {
    id: 'ar-playa-bonita',
    name: 'Playa Bonita',
    region: 'Bariloche, Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -41.121, lng: -71.402,
    water: 'choppy',
    waterDesc: 'Lago con chop y fondo de piedras.',
    wind: 'O / NO / SO',
    windMin: 15, windMax: 30,
    level: 'Intermedio',
    caution: 'Muy concurrida por turistas en verano. Agua fria.',
  },
  {
    id: 'ar-rivermouth-limay',
    name: 'Rivermouth (desembocadura del Limay)',
    region: 'Nahuel Huapi, Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -41.096, lng: -71.171,
    water: 'mixta',
    waterDesc: 'Cruce de la corriente del rio con las olas del lago.',
    wind: 'O / NO',
    windMin: 15, windMax: 35,
    level: 'Intermedio',
    caution: 'Corriente de salida del rio muy fuerte.',
  },
  {
    id: 'ar-varadero',
    name: 'Varadero',
    region: 'Bariloche, Rio Negro',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -41.128, lng: -71.265,
    water: 'choppy',
    waterDesc: 'Lago con chop y costa de pedregullo.',
    wind: 'O / NO',
    windMin: 15, windMax: 30,
    level: 'Intermedio',
    caution: 'Agua fria y rafagas cambiantes cerca de la orilla.',
  },
  {
    id: 'ar-navarro',
    name: 'Navarro',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.831, lng: -59.278,
    water: 'plana',
    waterDesc: 'Laguna chica de agua plana.',
    wind: 'Casi cualquier direccion no tapada por la arboleda',
    windMin: 10, windMax: 20,
    level: 'Principiante',
    caution: 'Laguna pequena con barro. Arboles en el perimetro de armado.',
  },
  {
    id: 'ar-necochea',
    name: 'Necochea',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.5721, lng: -58.7061,
    water: 'olas',
    waterDesc: 'Mar abierto con olas de buen tamano.',
    wind: 'E / SE / S / NE',
    windMin: 15, windMax: 32,
    level: 'Avanzado',
    caution: 'Deriva costera intensa.',
  },
  {
    id: 'ar-pinamar',
    name: 'Pinamar (La Frontera)',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.0781, lng: -56.848,
    water: 'olas',
    waterDesc: 'Mar abierto con rompiente fuerte.',
    wind: 'NE / E / SE / S',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Alto transito de vehiculos 4x4 en la playa de despegue.',
  },
  {
    id: 'ar-playa-grande',
    name: 'Playa Grande',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.0261, lng: -57.531,
    water: 'olas',
    waterDesc: 'Rompiente clasica de Mar del Plata.',
    wind: 'E / SE / NE',
    windMin: 15, windMax: 28,
    level: 'Avanzado',
    caution: 'Rodeada por las escolleras del puerto. Mucho surfista y banista.',
  },
  {
    id: 'ar-playa-horizonte',
    name: 'Playa Horizonte',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.078, lng: -57.5465,
    water: 'olas',
    waterDesc: 'Mar abierto con olas medianas.',
    wind: 'E / SE / S / NE',
    windMin: 15, windMax: 30,
    level: 'Intermedio',
    caution: 'Corriente de deriva.',
  },
  {
    id: 'ar-puerto-cardiel',
    name: 'Puerto Cardiel',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.982, lng: -57.541,
    water: 'olas',
    waterDesc: 'Mar abierto junto a acantilados bajos.',
    wind: 'E / SE / NE',
    windMin: 15, windMax: 28,
    level: 'Avanzado',
    caution: 'Escolleras rocosas cerca de la zona de navegacion.',
  },
  {
    id: 'ar-puerto-velas',
    name: 'Puerto Velas',
    region: 'Berisso, Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.8621, lng: -57.8821,
    water: 'choppy',
    waterDesc: 'Rio de la Plata con agua marron y chop.',
    wind: 'SE / E / NE',
    windMin: 12, windMax: 22,
    level: 'Principiante',
    caution: 'Piedras y vegetacion en el area de salida. Fondo de lodo.',
  },
  {
    id: 'ar-punta-mogotes',
    name: 'Punta Mogotes',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.055, lng: -57.543,
    water: 'olas',
    waterDesc: 'Playa extensa con rompientes importantes.',
    wind: 'E / SE / NE / S',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Corrientes de retorno (chupones) en la rompiente.',
  },
  {
    id: 'ar-punta-rasa',
    name: 'Punta Rasa',
    region: 'San Clemente del Tuyu, Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -36.2961, lng: -56.775,
    water: 'mixta',
    waterDesc: 'Ria de agua plana de un lado y mar abierto del otro. Funciona con viento de 360 grados.',
    wind: 'Todas las direcciones',
    windMin: 14, windMax: 32,
    level: 'Todos',
    caution: 'Corrientes extremadamente fuertes en la punta donde se cruza el rio con el mar. La ria se seca en marea baja.',
  },
  {
    id: 'ar-quequen',
    name: 'Quequen',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.561, lng: -58.688,
    water: 'olas',
    waterDesc: 'Olas potentes y grandes de mar abierto.',
    wind: 'E / SE / S / NE',
    windMin: 15, windMax: 35,
    level: 'Avanzado',
    caution: 'Planchones de piedra cerca de la orilla.',
  },
  {
    id: 'ar-quilmes',
    name: 'Quilmes',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -34.7214, lng: -58.2541,
    water: 'choppy',
    waterDesc: 'Rio de la Plata con chop y bajo fondo.',
    wind: 'E / SE / NE',
    windMin: 10, windMax: 20,
    level: 'Principiante',
    caution: 'Costa urbana con escombros en la orilla. Fondo de lodo y poca profundidad.',
  },
  {
    id: 'ar-rambla-catalunya',
    name: 'Rambla Catalunya',
    region: 'Rosario, Santa Fe',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -32.898, lng: -60.678,
    water: 'choppy',
    waterDesc: 'Salida desde la costa rosarina sobre el Parana.',
    wind: 'E / SE',
    windMin: 12, windMax: 22,
    level: 'Avanzado',
    caution: 'Transito intenso de lanchas y nadadores. Corrientes rapidas del Parana.',
  },
  {
    id: 'ar-arazati',
    name: 'Rio Parana / Arazati',
    region: 'Corrientes',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -27.475, lng: -58.841,
    water: 'choppy',
    waterDesc: 'Rio ancho con chop y corriente rapida.',
    wind: 'N / NE / S / SE',
    windMin: 10, windMax: 20,
    level: 'Intermedio',
    caution: 'Corriente muy rapida y buques mercantes en el canal.',
  },
  {
    id: 'ar-santa-clara',
    name: 'Santa Clara del Mar',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.8381, lng: -57.502,
    water: 'olas',
    waterDesc: 'Mar abierto con escolleras en T.',
    wind: 'E / SE / NE',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'Las escolleras generan corrientes de chupa y zonas de turbulencia.',
  },
  {
    id: 'ar-villa-gesell',
    name: 'Villa Gesell',
    region: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -37.2621, lng: -56.9721,
    water: 'olas',
    waterDesc: 'Rompiente costera de mar abierto.',
    wind: 'NE / E / SE / S',
    windMin: 14, windMax: 28,
    level: 'Intermedio',
    caution: 'La marea alta reduce mucho el espacio de playa. Banistas en temporada.',
  },
  {
    id: 'ar-waikiki',
    name: 'Waikiki',
    region: 'Mar del Plata',
    country: 'Argentina',
    flag: '🇦🇷',
    lat: -38.0801, lng: -57.546,
    water: 'olas',
    waterDesc: 'Rompiente sobre plataforma de piedra.',
    wind: 'E / SE / S',
    windMin: 15, windMax: 30,
    level: 'Avanzado',
    caution: 'Fondo de restingas (plataforma de piedra) y muchos surfistas.',
  },
];

// ============================================================
// TAMAÑOS DE KITE SEGÚN EL VIENTO
// Referencia para un rider de ~70–80 kg con tabla twintip.
// Si pesás más, subí un tamaño; si pesás menos, bajá uno.
// ============================================================

export const KITE_TABLE = [
  {
    min: 11, max: 15,
    kites: '14m a 17m (o foil / Flysurfer)',
    label: 'Lightwind',
    desc: 'Viento suave. Se necesita tabla grande (door) o hidrofoil para ceñir bien.',
    color: '#34C759',
  },
  {
    min: 15, max: 20,
    kites: '12m',
    label: 'Clásico',
    desc: 'El día perfecto. Ideal para progresar y saltar con comodidad.',
    color: '#00BCD4',
  },
  {
    min: 20, max: 25,
    kites: '9m a 10m',
    label: 'Viento fuerte',
    desc: 'El agua se pica bastante (chop alto). Divertido pero exige más piernas.',
    color: '#FF9500',
  },
  {
    min: 25, max: 30,
    kites: '7m a 8m',
    label: 'Extremo',
    desc: 'Condición "storm chaser". Mucho cuidado con las rachas si el viento rota.',
    color: '#FF3B30',
  },
  {
    min: 30, max: 99,
    kites: '5m a 6m',
    label: 'Solo expertos',
    desc: 'Viento muy fuerte. Solo con experiencia, equipo chico y compañía en la playa.',
    color: '#8E0000',
  },
];

// Devuelve las filas de la tabla que se cruzan con el rango de viento del spot
export function kitesForSpot(spot) {
  return KITE_TABLE.filter((r) => r.min < spot.windMax && r.max > spot.windMin);
}

// Vista inicial: toda Latinoamérica
export const LATAM_REGION = {
  latitude: -12,
  longitude: -62,
  latitudeDelta: 75,
  longitudeDelta: 75,
};

export const COUNTRIES = [...new Set(SPOTS.map((s) => s.country))].sort();

export const WATER_LABEL = {
  plana: 'Agua plana',
  choppy: 'Choppy',
  olas: 'Olas',
  mixta: 'Mixta',
};

export const WATER_COLOR = {
  plana: '#00BCD4',
  choppy: '#FF9500',
  olas: '#FF3B30',
  mixta: '#34C759',
};

export const LEVEL_COLOR = {
  Principiante: '#34C759',
  Todos: '#00BCD4',
  Intermedio: '#FFCC00',
  Avanzado: '#FF9500',
  Experto: '#FF3B30',
};
